/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.table.DefaultTableModel;

import dao.Thuoc_DAO;
import entities.Thuoc;

/**
 *
 * @author NguyenThanhLuan
 */
public class GUI_TimKiemThuoc extends javax.swing.JPanel {
	private DefaultTableModel modelThuoc;
	private Thuoc_DAO thuoc_DAO;
	private ArrayList<Thuoc> thuocs;
    /**
     * Creates new form GUI_TimKiemThuoc
     */
	private SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
	
	private String layNgayHienTai() {
		Date ngayHienTai = new Date();
		return sdf.format(ngayHienTai);
	}
	
	private void loadDuLieu() {
		 tableThuoc.removeAll();
		 tableThuoc.setRowSelectionAllowed(false);
		 modelThuoc.setRowCount(0);
	     thuocs = thuoc_DAO.layTatCaThuoc();
	     int stt = 1;
	     for(Thuoc thuoc : thuocs) {
	    	 modelThuoc.addRow(new Object[] {stt++, thuoc.getMaThuoc(), thuoc.getTenThuoc(), thuoc.getLoaiThuoc(), thuoc.getDonViThuoc(), thuoc.getXuatXu(), thuoc.getSoLuongTon(), thuoc.getNhaCungCap().getMaNCC(), thuoc.getNhaCungCap().getTenNCC()});
	     }
	}
    public GUI_TimKiemThuoc() {
        initComponents();
        thuoc_DAO = new Thuoc_DAO();
        loadDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ALL = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jTextField1 = new javax.swing.JTextField(layNgayHienTai());
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        jTextField2 = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jLabel5 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        jComboBox1 = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jLabel6 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        jComboBox2 = new javax.swing.JComboBox<>();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jLabel7 = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        jTextField4 = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThuoc = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setLayout(new java.awt.BorderLayout());

        ALL.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(444, 145));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/pngegg.png"))); // NOI18N
        jPanel8.add(jLabel1);

        jPanel4.add(jPanel8);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 102, 165));
        jLabel2.setText("DANH SÁCH THUỐC");
        jPanel6.add(jLabel2);

        jPanel4.add(jPanel6);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Ngày hiện tại");
        jPanel7.add(jLabel3);
        jPanel7.add(filler1);

        jTextField1.setMinimumSize(new java.awt.Dimension(180, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(180, 22));
        jPanel7.add(jTextField1);

        jPanel5.add(jPanel7);

        jPanel4.add(jPanel5);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 30, 8, 8));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Mã thuốc: ");
        jPanel12.add(jLabel4);
        jPanel12.add(filler5);
        jPanel12.add(jTextField2);
        jPanel12.add(filler4);

        jLabel5.setText("Loại thuốc:");
        jPanel12.add(jLabel5);
        jPanel12.add(filler7);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(220, 22));
        jComboBox1.setPreferredSize(new java.awt.Dimension(220, 22));
        jPanel12.add(jComboBox1);
        jPanel12.add(filler3);

        jLabel6.setText("Xuất xứ: ");
        jPanel12.add(jLabel6);
        jPanel12.add(filler8);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(220, 22));
        jComboBox2.setPreferredSize(new java.awt.Dimension(220, 22));
        jPanel12.add(jComboBox2);
        jPanel12.add(filler9);

        jLabel7.setText("Tên nhà cung cấp: ");
        jPanel12.add(jLabel7);
        jPanel12.add(filler10);
        jPanel12.add(jTextField4);
        jPanel12.add(filler2);

        jButton1.setText("Tìm kiếm");
        jButton1.setMaximumSize(new java.awt.Dimension(79, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(79, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(79, 30));
        jPanel12.add(jButton1);

        jPanel2.add(jPanel12, java.awt.BorderLayout.CENTER);

        ALL.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel34.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết hóa đơn"));
        jPanel34.setLayout(new java.awt.BorderLayout());

        tableThuoc.setModel(modelThuoc =new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã thuốc", "Tên thuốc", "Loại thuốc", "Đơn vị thuốc", "Xuất xứ", "Số lượng tồn",
                "Mã nhà cung cấp", "Tên nhà cung cấp"
            }
        ));
        jScrollPane1.setViewportView(tableThuoc);

        jPanel34.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton2.setText("Xem chi tiết");
        jPanel1.add(jButton2);
        jPanel1.add(filler6);

        jPanel34.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel34, java.awt.BorderLayout.CENTER);

        ALL.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(ALL, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALL;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tableThuoc;
    // End of variables declaration//GEN-END:variables
}
