/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JMenuItem;

/**
 *
 * @author NguyenThanhLuan
 */
public class GUI_TrangChu extends javax.swing.JFrame {
	private GUI_NhapThuoc gui_NhapThuoc;
	private GUI_BTN gui_BTN;
    /**
     * Creates new form GUI_TrangChu
     */
    public GUI_TrangChu() {
        initComponents();
        gui_BTN = new GUI_BTN();
        this.PnlChuyenHuong.add(gui_BTN);
        gui_NhapThuoc = new GUI_NhapThuoc();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlChuyenHuong = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTT = new javax.swing.JMenu();
        menuHD = new javax.swing.JMenu();
        menuSP = new javax.swing.JMenu();
        MenuItemNhapThuoc = new javax.swing.JMenuItem();
        menuKH = new javax.swing.JMenu();
        menuNV = new javax.swing.JMenu();
        menuNCC = new javax.swing.JMenu();
        menuTK = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlChuyenHuong.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PnlChuyenHuong, java.awt.BorderLayout.CENTER);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnDangXuat.setBackground(new java.awt.Color(15, 145, 239));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setPreferredSize(new java.awt.Dimension(160, 40));
        jPanel5.add(btnDangXuat);

        btnThoat.setBackground(new java.awt.Color(15, 145, 239));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.setPreferredSize(new java.awt.Dimension(160, 40));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel5.add(btnThoat);
        jPanel5.add(filler1);

        getContentPane().add(jPanel5, java.awt.BorderLayout.SOUTH);

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 255));
        jMenuBar1.setMargin(new java.awt.Insets(0, 8, 0, 8));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 45));

        menuTT.setForeground(new java.awt.Color(15, 145, 239));
        menuTT.setText("Trang chủ");
        menuTT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuTT.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menuTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTTActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuTT);

        menuHD.setForeground(new java.awt.Color(15, 145, 239));
        menuHD.setText("Hóa đơn");
        menuHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuHD.setMargin(new java.awt.Insets(3, 10, 3, 10));
        jMenuBar1.add(menuHD);

        menuSP.setForeground(new java.awt.Color(15, 145, 239));
        menuSP.setText("Sản phẩm");
        menuSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuSP.setMargin(new java.awt.Insets(3, 10, 3, 10));

        MenuItemNhapThuoc.setText("Nhập thuốc");
        MenuItemNhapThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNhapThuocActionPerformed(evt);
            }
        });
        menuSP.add(MenuItemNhapThuoc);

        jMenuBar1.add(menuSP);

        menuKH.setForeground(new java.awt.Color(15, 145, 239));
        menuKH.setText("Khách hàng");
        menuKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuKH.setMargin(new java.awt.Insets(3, 10, 3, 10));
        jMenuBar1.add(menuKH);

        menuNV.setForeground(new java.awt.Color(15, 145, 239));
        menuNV.setText("Nhân viên");
        menuNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuNV.setMargin(new java.awt.Insets(3, 10, 3, 10));
        jMenuBar1.add(menuNV);

        menuNCC.setForeground(new java.awt.Color(15, 145, 239));
        menuNCC.setText("Nhà cung cấp");
        menuNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuNCC.setMargin(new java.awt.Insets(3, 10, 3, 10));
        jMenuBar1.add(menuNCC);

        menuTK.setForeground(new java.awt.Color(15, 145, 239));
        menuTK.setText("Thống kê");
        menuTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuTK.setMargin(new java.awt.Insets(3, 10, 3, 10));
        jMenuBar1.add(menuTK);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
	private void clearSelectedMenu() {
		menuHD.setSelected(false);
		menuSP.setSelected(false);
		menuKH.setSelected(false);
		menuNV.setSelected(false);
		menuNCC.setSelected(false);
		menuTK.setSelected(false);
	}
    
	public void thayDoiPanelChinh(JComponent component, JMenuItem menu) {
		clearSelectedMenu();
		menu.setSelected(true);
		this.PnlChuyenHuong.removeAll();
		this.PnlChuyenHuong.repaint();
		this.PnlChuyenHuong.revalidate();

		this.PnlChuyenHuong.add(component);
		this.PnlChuyenHuong.repaint();
		this.PnlChuyenHuong.revalidate();
	}
	
    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void menuTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTTActionPerformed
    	this.thayDoiPanelChinh(gui_BTN, menuTT);
    }//GEN-LAST:event_menuTTActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
    	this.thayDoiPanelChinh(gui_BTN, menuTT);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnNhapThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapThuocActionPerformed
    	this.thayDoiPanelChinh(gui_NhapThuoc, menuSP);
    }//GEN-LAST:event_btnNhapThuocActionPerformed

    private void MenuItemNhapThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNhapThuocActionPerformed
    	this.thayDoiPanelChinh(gui_NhapThuoc, menuSP);
    }//GEN-LAST:event_MenuItemNhapThuocActionPerformed

    private void menuSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSPActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemNhapThuoc;
    private javax.swing.JPanel PnlChuyenHuong;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnThoat;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu menuHD;
    private javax.swing.JMenu menuKH;
    private javax.swing.JMenu menuNCC;
    private javax.swing.JMenu menuNV;
    private javax.swing.JMenu menuSP;
    private javax.swing.JMenu menuTK;
    private javax.swing.JMenu menuTT;
    // End of variables declaration//GEN-END:variables
}
