/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.table.DefaultTableModel;

import dao.Thuoc_DAO;
import entities.Thuoc;

/**
 *
 * @author NguyenThanhLuan
 */
public class GUI_TimKiemThuoc extends javax.swing.JPanel {
	private DefaultTableModel modelThuoc;
	private Thuoc_DAO thuoc_DAO = new Thuoc_DAO();
	private ArrayList<Thuoc> thuocs = new ArrayList<Thuoc>();
    /**
     * Creates new form GUI_TimKiemThuoc
     */
	private SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
	
	private String layNgayHienTai() {
		Date ngayHienTai = new Date();
		return sdf.format(ngayHienTai);
	}
	
	private void loadDuLieu() {
		 tableThuoc.removeAll();
		 tableThuoc.setRowSelectionAllowed(false);
		 modelThuoc.setRowCount(0);
	     thuocs = thuoc_DAO.layTatCaThuoc();
	     int stt = 1;
	     for(Thuoc thuoc : thuocs) {
	    	 modelThuoc.addRow(new Object[] {stt++, thuoc.getMaThuoc(), thuoc.getTenThuoc(), thuoc.getLoaiThuoc(), thuoc.getDonViThuoc(), thuoc.getXuatXu(), thuoc.getSoLuongTon(), thuoc.getNhaCungCap().getMaNCC(), thuoc.getNhaCungCap().getTenNCC()});
	     }
	}
	
	private void doDuLieuLenXuatXu() {
	      ArrayList<String> list = new ArrayList<>();

	        for (Thuoc thuoc : thuocs) {
	            // Kiểm tra xem list có tồn tại chưa
	            if (list == null) {
	                list = new ArrayList<>();
	            }
	            // Kiểm tra xem xuatXu đã được thêm vào list chưa
	            if (!list.contains(thuoc.getXuatXu())) {
	                list.add(thuoc.getXuatXu());
	            }
	        }

	        // Đổ dữ liệu từ list vào comboBox
	        for (String xuatXu : list) {
	            cbXuatXU.addItem(xuatXu);
	        }
	    }
	
	private ArrayList<Thuoc> timkiem() {
		ArrayList<Thuoc> dsTimKiem = new ArrayList<Thuoc>();
		String maThuoc = txtMaThuoc.getText();
		String loai = cbLoaiThuoc.getSelectedItem().toString();
		Object txtXuaXu = cbXuatXU.getSelectedItem();
		String maNCC = txtNhaCungCap.getText();
		if(maThuoc.length() > 0) {
			for(Thuoc thuoc : thuocs) {
				if(thuoc.getMaThuoc().contains(maThuoc) && thuoc.getLoaiThuoc().equals(loai))
					dsTimKiem.add(thuoc);
			}
		}	
		if(txtXuaXu != null) {
			String xuatXu = txtXuaXu.toString();
			for(Thuoc thuoc : thuocs) {
				if(thuoc.getXuatXu().equals(xuatXu) && thuoc.getLoaiThuoc().equals(loai))
					dsTimKiem.add(thuoc);
			}
			if(maThuoc.length() > 0) {
				dsTimKiem.clear();
				for(Thuoc thuoc : thuocs) {
					if(thuoc.getXuatXu().equals(xuatXu) && thuoc.getLoaiThuoc().equals(loai) && thuoc.getMaThuoc().contains(maThuoc))
						dsTimKiem.add(thuoc);
				}
			}
		}
		if(maNCC.length() > 0) {
			for(Thuoc thuoc : thuocs) {
				if(thuoc.getNhaCungCap().getMaNCC().contains(maNCC) && thuoc.getLoaiThuoc().equals(loai))
					dsTimKiem.add(thuoc);
			}
			if(maThuoc.length() > 0) {
				dsTimKiem.clear();
				for(Thuoc thuoc : thuocs) {
					if(thuoc.getNhaCungCap().getMaNCC().contains(maNCC) && thuoc.getLoaiThuoc().equals(loai) && thuoc.getMaThuoc().contains(maThuoc))
						dsTimKiem.add(thuoc);
				}
			}
			if(txtXuaXu != null) {
				String xuatXu = txtXuaXu.toString();
				dsTimKiem.clear();
				for(Thuoc thuoc : thuocs) {
					if(thuoc.getNhaCungCap().getMaNCC().contains(maNCC) && thuoc.getLoaiThuoc().equals(loai) && thuoc.getXuatXu().equals(xuatXu))
						dsTimKiem.add(thuoc);
				}
			}
			if(txtXuaXu != null && maThuoc.length() > 0) {
					String xuatXu = txtXuaXu.toString();
					dsTimKiem.clear();
					for(Thuoc thuoc : thuocs) {
						if(thuoc.getNhaCungCap().getMaNCC().contains(maNCC) && thuoc.getLoaiThuoc().equals(loai) && thuoc.getXuatXu().equals(xuatXu) && thuoc.getMaThuoc().contains(maThuoc))
							dsTimKiem.add(thuoc);
					}
				}
			}
			if(txtXuaXu == null && maThuoc.length() < 0 && maNCC.length() <0) {
				dsTimKiem.clear();
				for(Thuoc thuoc : thuocs) {
					if( thuoc.getLoaiThuoc().equals(loai))
						dsTimKiem.add(thuoc);
				}
			}
				
		return dsTimKiem;
	}
	
    public GUI_TimKiemThuoc() {
        initComponents();
        thuocs = thuoc_DAO.layTatCaThuoc();
        loadDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ALL = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jTextField1 = new javax.swing.JTextField(layNgayHienTai());
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        txtMaThuoc = new javax.swing.JTextField();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jLabel5 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        cbLoaiThuoc = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jLabel6 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        cbXuatXU = new javax.swing.JComboBox<>();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        jLabel7 = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        txtNhaCungCap = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btnTimKiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThuoc = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Reset = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setLayout(new java.awt.BorderLayout());

        ALL.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(444, 145));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhanvien/pngegg.png"))); // NOI18N
        jPanel8.add(jLabel1);

        jPanel4.add(jPanel8);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 102, 165));
        jLabel2.setText("DANH SÁCH THUỐC");
        jPanel6.add(jLabel2);

        jPanel4.add(jPanel6);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Ngày hiện tại");
        jPanel7.add(jLabel3);
        jPanel7.add(filler1);

        jTextField1.setMinimumSize(new java.awt.Dimension(180, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(180, 22));
        jPanel7.add(jTextField1);

        jPanel5.add(jPanel7);

        jPanel4.add(jPanel5);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 30, 8, 8));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Mã thuốc: ");
        jPanel12.add(jLabel4);
        jPanel12.add(filler5);
        jPanel12.add(txtMaThuoc);
        jPanel12.add(filler4);

        jLabel5.setText("Loại thuốc:");
        jPanel12.add(jLabel5);
        jPanel12.add(filler7);

        cbLoaiThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thuốc kê đơn", "Thuốc không kê đơn", "Thực phẩm chức năng", "Chăm sóc sức khỏe" }));
        cbLoaiThuoc.setMinimumSize(new java.awt.Dimension(220, 22));
        cbLoaiThuoc.setPreferredSize(new java.awt.Dimension(220, 22));
        jPanel12.add(cbLoaiThuoc);
        jPanel12.add(filler3);

        jLabel6.setText("Xuất xứ: ");
        jPanel12.add(jLabel6);
        jPanel12.add(filler8);

        cbXuatXU.setMinimumSize(new java.awt.Dimension(220, 22));
        cbXuatXU.setPreferredSize(new java.awt.Dimension(220, 22));
        cbXuatXU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbXuatXUMouseClicked(evt);
            }
        });
        cbXuatXU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbXuatXUActionPerformed(evt);
            }
        });
        jPanel12.add(cbXuatXU);
        jPanel12.add(filler9);

        jLabel7.setText("Tên nhà cung cấp: ");
        jPanel12.add(jLabel7);
        jPanel12.add(filler10);
        jPanel12.add(txtNhaCungCap);
        jPanel12.add(filler2);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setMaximumSize(new java.awt.Dimension(79, 35));
        btnTimKiem.setMinimumSize(new java.awt.Dimension(79, 30));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(79, 35));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel12.add(btnTimKiem);

        jPanel2.add(jPanel12, java.awt.BorderLayout.CENTER);

        ALL.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel34.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết hóa đơn"));
        jPanel34.setLayout(new java.awt.BorderLayout());

        tableThuoc.setModel(modelThuoc =new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã thuốc", "Tên thuốc", "Loại thuốc", "Đơn vị thuốc", "Xuất xứ", "Số lượng tồn",
                "Mã nhà cung cấp", "Tên nhà cung cấp"
            }
        ));
        jScrollPane1.setViewportView(tableThuoc);

        jPanel34.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        Reset.setText("Reset table");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel1.add(Reset);
        jPanel1.add(filler6);

        jPanel34.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel34, java.awt.BorderLayout.CENTER);

        ALL.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(ALL, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbXuatXUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbXuatXUActionPerformed
        // TODO add your handling code here:
        doDuLieuLenXuatXu();
    }//GEN-LAST:event_cbXuatXUActionPerformed

    private void cbXuatXUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbXuatXUMouseClicked
        // TODO add your handling code here:
        doDuLieuLenXuatXu();
    }//GEN-LAST:event_cbXuatXUMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    	 ArrayList<Thuoc> list = new ArrayList<Thuoc>();
    	 tableThuoc.removeAll();
         tableThuoc.setRowSelectionAllowed(false);
         modelThuoc.setRowCount(0);
         list = timkiem();
         int stt = 1;
	     for(Thuoc thuoc : list) {
	    	 modelThuoc.addRow(new Object[] {stt++, thuoc.getMaThuoc(), thuoc.getTenThuoc(), thuoc.getLoaiThuoc(), thuoc.getDonViThuoc(), thuoc.getXuatXu(), thuoc.getSoLuongTon(), thuoc.getNhaCungCap().getMaNCC(), thuoc.getNhaCungCap().getTenNCC()});
	     }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        loadDuLieu();
    }//GEN-LAST:event_ResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALL;
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbLoaiThuoc;
    private javax.swing.JComboBox<String> cbXuatXU;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableThuoc;
    private javax.swing.JTextField txtMaThuoc;
    private javax.swing.JTextField txtNhaCungCap;
    // End of variables declaration//GEN-END:variables
}
